# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-23 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodic_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictask',
            name='last_run_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
