# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-23 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import periodic_tasks.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('persollo.periodic_tasks.periodic_task_test', 'persollo.periodic_tasks.periodic_task_test')], max_length=256)),
                ('arguments', models.CharField(blank=True, default='', max_length=256)),
                ('crontab_string', models.CharField(blank=True, default='* * * * *', max_length=256, validators=[periodic_tasks.validators.validate_crontab_string])),
                ('next_run_timestamp', models.IntegerField(blank=True, null=True)),
                ('is_one_time_run', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
